'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class 商品
    Public Property Id As Integer
    Public Property 分類 As String
    Public Property 商品名 As String
    Public Property 単価 As Integer
    Public Property 数量 As Integer

End Class
