'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class 商品
    Public Property 商品ID As Integer
    Public Property 商品名 As String
    <Range(100, 1000,
           ErrorMessage:="{0}は{1}から{2}までの間で指定してください")>
    Public Property 単価 As Integer
End Class
